# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
  - r: oldrel 
  - r: release
  - r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
