# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nsignC <- function(x) {
    .Call('inferr_nsignC', PACKAGE = 'inferr', x)
}

gvar <- function(ln, ly) {
    .Call('inferr_gvar', PACKAGE = 'inferr', ln, ly)
}

